### ISSUE TITLE
Support writer customization using `--storage-config-file`

### ISSUE THREAD

**Issue by jtbandes** [ros-tooling/rosbag2_storage_mcap#35]
The MCAP plugin should support customizing MCAP [writer options](https://github.com/foxglove/mcap/blob/152b9d1820b8cbf485dc23dad2be1cc03d738483/cpp/mcap/include/mcap/writer.hpp#L15-L93) using the `--storage-config-file` argument, which allows input of an arbitrary file that is passed to the storage implementation, for `ros2 bag play` and `ros2 bag record`

In code this can be accessed via [`StorageOptions::storage_config_uri`](https://github.com/ros2/rosbag2/blob/4e4619b6b60746ca7ae67fc7821ac0b8b69d0531/rosbag2_storage/include/rosbag2_storage/storage_options.hpp).

Example from SQLite plugin which parses the file as YAML:
https://github.com/ros2/rosbag2/blob/e385df81408090609ee628a54d315b8e898f3215/rosbag2_storage_default_plugins/src/rosbag2_storage_default_plugins/sqlite/sqlite_storage.cpp#L75

**Comment by amacneil** [comment]
Also worth considering whether we should add a more structured way for rosbag2 plugins to implement options? Can't do this for Humble, but we could change it in Rolling.

**Comment by emersonknapp** [comment]
Just rewrote the title/description to match current state of things more accurately.

Allowing plugins to register commandline arguments could be a cool feature, but I don't have a strong sense of how it would look in practice. I have repurposed https://github.com/ros2/rosbag2/issues/276 for this enhancement, but it's more questions than statements at the moment.

I'll get started for first pass milestone with accepting a `--storage-config-file` input and parsing that as `mcap::McapWriterOptions`

**Comment by jtbandes** [comment]
The initial description wasn't intended to be custom handling of command line arguments per se. I just saw that there was already a `--output-options` flag (https://github.com/ros2/rosbag2#converting-bags) and it seemed like the appropriate place to put mcap options. But I guess `--storage-config-file` also sounds relevant. 👍

**Comment by emersonknapp** [comment]
Oh I see where you got that. --output-options is explicitly configuration for the convert verb. But storage config file is universal to use of storage impls. It can be provided within the output-options file for conversion
