### ISSUE TITLE
Can I get write access to this repo?

### ISSUE THREAD

**Issue by amacneil** [ros-tooling/rosbag2_storage_mcap#40]
## Description
Mostly I only need issue admin, rather than pushing code. I think a repo admin will need to add me.

**Comment by christophebedard** [comment]
@amacneil I gave you "triage" permission, but I can give you write access if you want. There's an "mcap" team (at the org level), but I don't think I have the right permissions to add people to it.

**Comment by amacneil** [comment]
thanks!
