### ISSUE TITLE
Add support for IDL messages

### ISSUE THREAD

**Issue by defunctzombie** [ros-tooling/rosbag2_storage_mcap#43]
## Description

MCAP recording only handles .msg files for schema records `data`.

The current mcap spec only has `ros2msg` as a schema encoding: https://github.com/foxglove/mcap/blob/main/docs/specification/appendix.md#ros2msg

## Related Issues

https://github.com/foxglove/mcap/issues/496

## Completion Criteria

If I author an IDL file in my ROS codebase I should be able to have that recorded in my mcap file.

**Comment by james-rms** [comment]
`ros2idl` is now present in the spec, and IDL message schemas are recorded by the `rosbag2_storage_mcap` plugin v0.3.0.
