### ISSUE TITLE
amazon.com copyright? 

### ISSUE THREAD

**Issue by kachess** [ros-tooling/rosbag2_storage_mcap#44]
## Description
** clear and concise description of the bug is **
In [rosbag2_storage_mcap/src/mcap_storage.cpp](https://github.com/ros-tooling/rosbag2_storage_mcap/blob/4ce5623a0a4e38d022635527310ace729ae38a0d/rosbag2_storage_mcap/src/mcap_storage.cpp), it shows "Copyright 2022, Amazon.com Inc or its Affiliates"
### Expected Behavior
** clear and concise description of what you _expected_ to happen **
not sure it is really amazon related
### Actual Behavior
** clear and concise description of what _actually_ happened. include copied logs whenever possible **

## To Reproduce
** Steps to reproduce the behavior, e.g.
4. Logs print error '...' **

## System (please complete the following information)
 - OS: [e.g. Ubuntu Bionic]
 - ROS 2 Distro: [e.g. Dashing]
N/A
** For ROS 2 bugs - please attach a VCS.repos or Dockerfile if possible to help us reproduce the environment **

## Additional context
** Add any other context about the problem here **

**Comment by christophebedard** [comment]
That's just the official copyright owner since the file was (at least initially) contributed by an Amazon employee: https://github.com/ros-tooling/rosbag2_storage_mcap/pull/3/files#diff-70e39b7ca397cf77e9fe4158af0f24726e4dc37109f3bf894721564cc2d30a8a
