### ISSUE TITLE
undefined symbol: LZ4F_createDecompressionContext since MCAP 0.1.2 upgrade

### ISSUE THREAD

**Issue by emersonknapp** [ros-tooling/rosbag2_storage_mcap#45]
## Description
* https://github.com/foxglove/mcap/pull/482 , which was included in v0.1.2, added a new dependency on `lz4frames.h` (and its implementing `.c`)
*  https://github.com/ros-tooling/rosbag2_storage_mcap/pull/42 upgraded to this new version without incorporating the new sources, so we get an undefined symbol error when actually trying to read/play mcap bags

This is luckily not synced into Humble yet, but the latest bloomed version 0.1.6 includes this change, which will go out in the next sync.

I'm fixing it right now, just wanted to document the issue while I do so

**Comment by jtbandes** [comment]
😱  sorry about that

**Comment by emersonknapp** [comment]
No worries - this just highlights the need for an automated test suite. Relying on manual testing never works. Luckily there wasn't a Humble sync since the change so no customers should be impacted.

**Comment by jtbandes** [comment]
It does look like 0.1.6 went out in a Galactic sync though, if the badges on the readme are to be believed.

**Comment by emersonknapp** [comment]
Yes, you are right. There has been a Galactic sync since the release - but not Foxy or Humble. So, at least the LTS distros are still stable
