### ISSUE TITLE
Transient-local topics are not repeated into individual MCAP files when file splitting is enabled

### ISSUE THREAD

**Issue by jhurliman** [ros-tooling/rosbag2_storage_mcap#75]
## Description
Transient-local topics are not repeated into individual MCAP files when file splitting is enabled

### Expected Behavior
Transient-local topics are repeated into individual MCAP files when file splitting is enabled

### Actual Behavior
Transient-local topics are not repeated into individual MCAP files when file splitting is enabled

## To Reproduce
** Steps to reproduce the behavior, e.g.
1. Record a transient-local topic with file splitting enabled

## System (please complete the following information)
 - OS: All
 - ROS 2 Distro: All

**Comment by MichaelOrlov** [comment]
@jhurliman This is not a bug. This is a feature and we do this on purpose. See my detailed explanation here https://github.com/ros2/rosbag2/pull/1051#pullrequestreview-1059614100

**Comment by amacneil** [comment]
Related ticket in rosbag2: https://github.com/ros2/rosbag2/issues/1159

**Comment by james-rms** [comment]
Closing in favor of https://github.com/ros2/rosbag2/issues/1159
