### ISSUE TITLE
Store per-channel QoS profile metadata

### ISSUE THREAD

**Issue by jhurliman** [ros-tooling/rosbag2_storage_mcap#79]
## Description

The sqlite storage plugin stores QoS profile information in `.db3` files as well as `metadata.yml`. The mcap storage plugin should store QoS profile information in `.mcap` files, as `Channel` record metadata.

## Related Issues

Blocked on https://github.com/foxglove/mcap/issues/741

## Completion Criteria

 - [ ] All Channel records written by this plugin have include QoS profile metadata

**Comment by james-rms** [comment]
This confuses me - is the idea to store more than what is included here?

https://github.com/ros-tooling/rosbag2_storage_mcap/blob/main/rosbag2_storage_mcap/src/mcap_storage.cpp#L668

**Comment by james-rms** [comment]
Closing as already implemented.
