### ISSUE TITLE
Unable to use 0.5.0 in Foxy

### ISSUE THREAD

**Issue by haudren-woven** [ros-tooling/rosbag2_storage_mcap#82]
## Description
When using the `foxy-future` branch of `rosbag2` repository, I seem to be unable to run the 0.5.0 writer. This used to work fine in 0.4.0, so I expect the latest changes regarding the storage presets to have broken compatibility.

I have built from source:
- ros2/rosbag2@67564a4
- ros-tooling/rosbag2_storage_mcap@4b896fb

### Expected Behavior
When running:
```
ros2 bag record -a -s mcap
```
The bag should be recorded

### Actual Behavior
** clear and concise description of what _actually_ happened. include copied logs whenever possible **
The process crashes with:
```
[ERROR] [1669098459.085235336] [rosbag2_storage]: Could not open 'rosbag2_2022_11_22-15_27_39/rosbag2_2022_11_22-15_27_39_0' with 'mcap'. Error: unknown MCAP storage preset profile (valid options are 'fastwrite', 'zstd_fast', 'zstd_small'): none
[ERROR] [1669098459.085339323] [rosbag2_storage]: Could not load/open plugin with storage id 'mcap'.
[ERROR] [1669098459.085374560] [rosbag2_transport]: Failed to record: No storage could be initialized. Abort
```

## To Reproduce
See above :point_up: 

Suggested fixes:
- Interpret `none` the same as empty profile
- Backport https://github.com/ros2/rosbag2/pull/1135 into foxy-future

## System (please complete the following information)
 - OS: Ubuntu Focal
 - ROS 2 Distro: Foxy (rosbag2 futurized)

** For ROS 2 bugs - please attach a VCS.repos or Dockerfile if possible to help us reproduce the environment **

## Additional context
** Add any other context about the problem here **
Interestingly (this might be due to overlays) if instead of building the mcap storage plugin from source, I install it from deb, so:
- Build ros2/rosbag2@67564a4
- `apt install ros-foxy-rosbag2-storage-mcap`
The storage configuration appears to not be passed to the plugin at all. I guess it's due to overrides in the environment, but that made the bug more mysterious...

**Comment by FranzAlbers** [comment]
I'm running into the same error with version 0.5.0 installed from apt with ros2 humble.

I tried setting the storage-preset-profile, but this seems to be currently not possible until this fix (https://github.com/ros2/rosbag2/pull/1135)  is merged to humble.

**Comment by ckurtz22** [comment]
Also does not work in humble for me. I'm assuming the new zstd stuff is just not supported besides rolling/iron

**Comment by bertaveira** [comment]
did any of you find any short-term solution?

**Comment by ckurtz22** [comment]
> did any of you find any short-term solution?

I cloned the 0.4.0 version of this repository into my workspace and used that instead of the apt version.

**Comment by bjajoh** [comment]
Same issue here!

**Comment by bertaveira** [comment]
Thanks @ckurtz22 I was still getting the warning in the terminal so I assumed rolling back did not fix it but despite the warning, it works to go back to 0.4.0

**Comment by james-rms** [comment]
Hello all, apologies for the broken code. https://github.com/ros-tooling/rosbag2_storage_mcap/pull/86 has merged and is being bloomed now, which should fix the MCAP storage plugin in the next sync for your relevant distribution. You can also build the plugin from source from the latest `main` to work around this issue.

**Comment by ckurtz22** [comment]
Thank you @james-rms for the quick fix! I'm glad this is able to get fixed and merged upstream.

**Comment by james-rms** [comment]
Closing as no more work remains to do in this repo.
